# Generated by Django 3.2.4 on 2021-06-06 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artcile_header', models.CharField(max_length=50, verbose_name='Article header')),
                ('artcile_text', models.TextField(verbose_name='Article text')),
                ('publication_date', models.DateField(verbose_name='Publication Date')),
                ('likes', models.IntegerField(default=0, verbose_name='Likes on article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Article author')),
            ],
        ),
    ]
