# Generated by Django 3.2.4 on 2021-06-06 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='artcile_header',
            new_name='article_header',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='artcile_text',
            new_name='article_text',
        ),
    ]
