# Generated by Django 3.2.4 on 2021-06-07 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210606_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_header',
            new_name='article_title',
        ),
    ]
