# Generated by Django 3.2.4 on 2021-06-07 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_rename_article_header_article_article_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['publication_date'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
    ]
