# Generated by Django 3.2.4 on 2021-07-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20210617_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='hashtags',
            field=models.TextField(default='', verbose_name='Article hashtags'),
        ),
    ]
